### ISSUE TITLE
Google custom search api

### ISSUE THREAD

**Issue by william76101** [mvalipour/telegram-bot-simple#1]
Possible to include the Google custom search api for searching the image and then send it with photo?

I can't find around the solution. Can you advise on this? Thanks!!

**Comment by mvalipour** [comment]
have you tried [google-images](https://github.com/vadimdemedes/google-images)?

**Comment by william76101** [comment]
Hi, 

Yes i tried but can't send photo due to error message (Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: there is no photo in the request"}). Can you advise on this? Thanks!!

My source code: 

client.search('World')
        .then(function (images) {
            var photo1 = images;
            bot.sendPhoto(msg.chat.id, photo1, {caption: "test"});
        });

**Comment by mvalipour** [comment]
As per [`google-image`'s sample code](https://github.com/vadimdemedes/google-images#usage) `images` is an array of objects, each pointing to the image URL. and as per [`.sendPhoto()`'s docs](https://github.com/yagop/node-telegram-bot-api#TelegramBot+sendPhoto) you must pass to it either a [local] file path, a stream or a byte buffer.

You need to grab the url and use something like [`request`](https://github.com/request/request) to get the image stream (or hold it in a buffer in memory) and pass it on to the `.sendPhoto()` method.

something like:

```
client.search('World').then(function (images) {
    // gracefully handle of images.length === 0 ?
    var url = images[0].url;
    request.get().blahblah(function(stream) {
        bot.sendPhoto(msg.chat.id, stream, {caption: "test"});
    });
});
```

P.S.

To be honest, all of this conversation is outside of the context of this repo. If you need any further assistance, you would need to ask your question on StackOverflow and there would be plenty of people willing to help.
